<!-- esta es una pagina de terminos y condiciones donde esta informacion relevante -->
<html>
        <head>
        <title>Términos y Condiciones - Animalia.com</title>
        <meta name="robots" content="noindex, nofollow">
        </head>
        <body style="font-family: Helvetica, Arial, sans-serif; color: #333; max-width: 600px; margin: 2em auto 2em auto;">
        <h1>Términos y Condiciones</h1>
        <h2>1. Datos de identificación</h2>
        <p>Web creada por Enrique Sanchez para la umc</p>
        <p></p><h2>2. Qué es Animalia</h2>
        <p>Animalia nace con la vocación de facilitar a los usuarios información variada del mundo animal. Por este motivo, la filosofía de Animalia no es otra que la publicación, entre otros, de multitud de artículos, vídeos, reproducciones sonoras, programas y datos (en adelante, los "Contenidos") que ofrezcan consejos prácticos para la cria, adiestramiento y cuidado de los animales. Animalia se considera un proyecto que apuesta por un mundo en equilibrio entre hombre y animal.</p>
        <p>Por este motivo, nuestra política en cuanto a la publicación de Contenidos es muy estricta, de forma que, cada uno de los Contenidos que el usuario desee publicar será revisado por los editores de Animalia. Nos reservamos el derecho a modificar, borrar, editar total o parcialmente el contenido que los usuarios o colaboradores publiquen en la web.</p>
        <p>Desde Animalia hemos decidido no publicar en el Sitio Web aquellos Contenidos que versen sobre contenidos prohibidos según se definen éstos en el apartado 5.2, que infrinjan derechos de propiedad intelectual o cualesquiera otros derechos de terceros, o si así lo considera Animalia a su entera discreción.</p>
        <p>Por todo lo anterior, serán los editores de Animalia quienes, atendiendo a los criterios anteriores, decidirán qué Contenidos son publicados en el Sitio Web y cuáles no, siempre y cuando, dicha decisión de no publicar determinados Contenidos no suponga una discriminación hacia el usuario.</p><p></p>
        <h2>3. Aceptación de los Términos y Condiciones</h2>
        <p>3.1 El acceso y/o uso del Sitio Web está supeditado a los Términos y Condiciones que se expresan a continuación, a la Política de Privacidad, así como a la legislación vigente, y atribuye a quien accede, utiliza y/o aporta Contenidos al mismo la condición de usuario.</p>
        <p>3.2 Al acceder y/o utilizar el Sitio Web, el usuario acepta, sin reserva ni limitación, los presentes Términos y Condiciones y la Política de Privacidad.</p>
        <p>3.3 En caso de no aceptar los presentes Términos y Condiciones, el usuario deberá abstenerse de acceder y/o utilizar el Sitio Web, debiendo abandonarlo inmediatamente.</p>
        <p>3.4 El usuario no podrá utilizar el Sitio Web ni podrá aceptar los Términos y Condiciones si:</p>
        <p>(a) no está legalmente capacitado para celebrar un contrato vinculante con Animalia, o</p>
        <p>(b) el acceso, la utilización y/o la provisión de Contenidos pudiera ser contraria a la legislación que resultara serle de aplicación.</p>
        <p>3.5 Animalia se reserva la facultad de efectuar, en cualquier momento y sin necesidad de previo aviso, modificaciones y actualizaciones de la información contenida en el Sitio Web, así como de la configuración y presentación de ésta y de los términos y condiciones de acceso y uso a la misma. El usuario quedará obligado automáticamente por los términos y condiciones que se hallen vigentes en el momento en que acceda al Sitio Web, por lo que deberá leer periódicamente los presentes Términos y Condiciones.</p>
        <h2>4. Disponibilidad y accesibilidad del Sitio Web</h2>
        <p>4.1 El usuario del Sitio Web, mediante su acceso al mismo, se obliga a utilizarlo conforme con los presentes Términos y Condiciones, la Política de Privacidad y la legislación vigente y acepta que el uso del mismo, así como de sus Contenidos y/o servicios tiene lugar bajo su única y exclusiva responsabilidad asumiendo, frente a Animalia y/o frente a terceros, cualesquiera daños y perjuicios que se pudieran causar como consecuencia del incumplimiento de dicha obligación.</p>
        <p>4.2 El Sitio Web ofrece al usuario la posibilidad de registrarse. El usuario es responsable de aportar información veraz y exacta para su registro así como en la suscripción de cualquiera de los servicios disponibles en el Sitio Web. Asimismo, el usuario se responsabiliza de custodiar de manera diligente y confidencial su nombre de usuario y contraseña y de notificar a Animalia cualquier incidencia al respecto.</p>
        <p>4.3 Con el fin de proteger los derechos de los menores de edad, el Sitio Web puede contener determinadas secciones de acceso restringido para éstos.</p>
        <h2>5. Contenidos del Sitio Web</h2>
        <p>5.1 Animalia rechazará, se negará a publicar o eliminará cualesquiera Contenidos que versen sobre los contenidos detallados en el apartado siguiente, que infrinjan derechos de propiedad intelectual o cualesquiera otros derechos de terceros o si así lo considera Animalia a su entera discreción siempre que no suponga un acto discriminatorio.</p>
        <p>5.2 A modo enunciativo pero no limitativo, Animalia no publicará o procederá a eliminar Contenidos que:</p>
        <ol style="list-style-type: lower-roman;">
        <li>versen sobre contenido ofensivo o discriminatorio por razón de sexo, raza, religión o cualquier otra circunstancia social o personal,</li>
        <li>fomenten el acoso, el odio o la violencia física o psíquica, o sean abusivos o intimidatorios,</li>
        <li>sean falsos o engañosos o promuevan o versen sobre actividades ilegales, inmorales, atentatorias contra el orden público, abusivas, amenazadoras, violentas, pornográficas, obscenas, injuriosas, difamatorias o calumniosas,</li>
        <li>contengan información que represente o cree un riesgo para la privacidad o la seguridad de cualquier persona,</li>
        <li>contengan información que promueva la creación de virus informáticos o que en sí mismos contengan virus u otros archivos nocivos,</li>
        <li>impliquen actividades comerciales y/o ventas sin el consentimiento previo por escrito de Animalia, como concursos, sorteos, publicidad, esquemas piramidales u otros,</li>
        <li>impliquen la transmisión de “correo basura” o “cartas en cadena”, o el envío de mensajes no solicitados de correo masivo o “spamming”,</li>
        <li>ofrezcan páginas de acceso restringido o páginas o imágenes ocultas,</li>
        <li>incluyan datos personales, incluidos la imagen o video de otra persona sin contar con el consentimiento debido para ello,</li>
        <li>promuevan propagandas y/o símbolos de organizaciones inconstitucionales o ilegales,</li>
        <li>violen o promuevan la infracción de los derechos de propiedad intelectual o industrial, derechos al honor, a la intimidad, a la imagen, derechos comerciales, derechos contractuales o cualquier otro derecho de cualquier persona o entidad, y</li>
        <li>constituyan o promuevan comportamientos o actitudes que supongan malos tratos a animales o personas.</li>
        </ol>
        <p>5.3 Todos los Contenidos que el usuario desee publicar serán previamente revisados por Animalia, sin que ésta asuma responsabilidad alguna por dicha labor de revisión o moderación para detectar Contenidos que, a su juicio, puedan resultar ilícitos o inapropiados. Tampoco será responsable Animalia por los Contenidos finalmente publicados ni por la conducta del usuario respecto a los Contenidos publicados.</p>
        <p>5.4 En el supuesto en que los Contenidos pudieran estar vulnerando derechos de propiedad intelectual o cualesquiera otros derechos de terceras partes, Animalia los retirará del Sitio Web o impedirá el acceso a los mismos si un órgano competente así lo hubiera declarado, tal y como establece la normativa vigente.</p>
        <h2>6. Mecanismos de participación</h2>
        <p>6.1 El Sitio Web contiene foros y otras herramientas de participación.</p>
        <p>6.2 Los comentarios de los usuarios en los mecanismos de participación reflejan su opinión y no la opinión de Animalia, quien no se hace responsable de las opiniones publicadas por los usuarios en dichos mecanismos.</p>
        <p>6.3 Animalia se reserva el derecho a suprimir o editar aquellos comentarios que considere inadecuados. Se podrá cerrar en cualquier momento y sin previo aviso cualquiera de los espacios de discusión existentes en el Sitio Web. Asimismo, Animalia podrá vetar el acceso de aquellos usuarios que reincidan en una actitud inadecuada.</p>
        <h2>7. Cancelación de la cuenta de usuario</h2>
        <p>El usuario estará legitimado a cancelar, en cualquier momento, su cuenta en el Sitio Web mediante el mecanismo habilitado a tal efecto en el Sitio Web. La cancelación de la cuenta no faculta al usuario a retirar los Contenidos que hubiera proporcionado a Animalia, ya que los derechos de propiedad intelectual sobre los mismos recaen en Animalia.</p>
        <h2>8. Exención de responsabilidad</h2>
        <p>8.1 Animalia no será responsable de los daños derivados del uso del Sitio Web, ni de cualquier actuación realizada en base a la información que en el mismo se facilita.</p>
        <p>8.2 Animalia no se hace responsable de los posibles errores de seguridad o desconexiones que se puedan producir ni de los posibles daños que puedan causarse al sistema informático del usuario (hardware y software), los ficheros o documentos almacenados en el mismo, como consecuencia de la presencia de virus en el ordenador del usuario, utilizado para la conexión al Sitio Web, o de un mal funcionamiento del navegador o del uso de versiones no actualizadas del mismo.</p>
        <h2>9. Responsabilidad por enlaces desde otras páginas web a Animalia</h2>
        <p>9.1 El usuario que desee ofrecer Contenidos de Animalia en su propia página web podrá introducir en la misma un enlace que vincule su página web con la página de inicio del Sitio Web.</p>
        <p>9.2 Las páginas web que ofrezcan un enlace al Sitio Web podrán utilizar la marca, logotipo, nombre comercial y/o cualquier otro signo distintivo de Animalia única y exclusivamente en los casos autorizados legalmente o permitidos por Animalia expresamente.</p>
        <p>9.3 El usuario no podrá reproducir el Sitio Web de ningún modo en su propia página web ni podrá establecer frames o marcos de cualquier tipo que rodeen el Sitio Web o permitan visualizarlo a través de direcciones de Internet distintas o conjuntamente con contenidos ajenos al mismo, de manera que produzca o pueda producir error o confusión en el público sobre la procedencia de los Contenidos, implique un acto de comparación o imitación desleal, sirva para aprovechar la reputación y la marca de Animalia o se haga de cualquier otro modo prohibido por la legislación aplicable.</p>
        <p>9.4 El usuario que introduzca el enlace al Sitio Web no podrá efectuar bajo ningún concepto manifestaciones falsas o inexactas sobre Animalia, sobre sus integrantes y/o clientes ni sobre la calidad de los Contenidos ofrecidos.</p>
        <p>9.5 Las páginas web en las que se ofrezca el enlace al Sitio Web no ofrecerán contenidos ilícitos, nocivos, contrarios a la moral y a las buenas costumbres, que produzcan o puedan producir la falsa idea de que Animalia respalda o apoya las ideas, manifestaciones o actuaciones de dichos usuarios o que resulten inadecuados en relación con la actividad desarrollada por Animalia.</p>
        <h2>10. Responsabilidad por enlaces desde Animalia a otras páginas web</h2>
        <p>10.1 Con el objeto de ayudar al usuario a buscar otra información o servicios de interés, el Sitio Web podrá incluir hipervínculos o enlaces a otros sitios web que no son propiedad de Animalia ni están controlados por ésta. Animalia no controla los contenidos, las condiciones legales, las políticas de privacidad o las prácticas de los sitios web de terceros ni asume responsabilidad alguna por éstos.</p>
        <p>10.2 El usuario reconoce y acepta que el acceso a otros sitios web no supone que Animalia recomiende o apruebe el contenido de los mismos y que Animalia no será responsable de las pérdidas o daños que el usuario pudiera sufrir a consecuencia de la disponibilidad de los mencionados sitios web, o a consecuencia de la credibilidad que otorgue a la exhaustividad, precisión o existencia de cualquier información ofrecida a través de dichos sitios web.</p>
        <p>10.3 Animalia retirará del Sitio Web o impedirá el acceso a aquellos enlaces que remitan a actividades ilícitas o lesivas de derechos o bienes de un tercero siempre que un órgano competente así lo hubiera declarado, tal y como establece la normativa vigente.</p>
        <h2>11. Actividades prohibidas</h2>
        <p>11.1 El usuario no podrá llevar a cabo en el Sitio Web actividades delictivas o ilícitas, incluidas a título enunciativo pero no limitativo, pornografía infantil, corrupción de menores, fraude, tráfico de material obsceno, tráfico de drogas, juegos de azar, acoso, robo de secretos comerciales e industriales, spamming, envío de virus u otros archivos nocivos, infracción de derechos de propiedad intelectual e industrial, infracción de los derechos al honor, a la intimidad y a la imagen, así como a cualesquiera otros derechos.</p>
        <p>11.2 El usuario no podrá interferir o perturbar de ningún modo el hardware, software o las redes a través de las que se ofrezca el servicio del Sitio Web mediante el uso de virus, robots, gusanos o cualquier otro tipo de código, archivo o programa.</p>
        <p>11.3 El usuario no podrá evitar o modificar de forma que se evite cualquier tecnología o software de seguridad de Animalia ni colaborar en dichas tareas.</p>
        <p>11.4 El usuario no podrá suplantar o intentar suplantar la identidad del resto de usuarios en el Sitio Web.</p>
        <p>11.5 El usuario no podrá exhibir publicidad comercial no autorizada en el Sitio Web ni usar los Contenidos del Sitio Web con el fin de realizar publicidad comercial no autorizada o de otra forma, acosar, abusar o perjudicar a otra persona o entidad.</p>
        <h2>12. Menores</h2>
        <p>El Sitio Web está dirigido a usuarios mayores de catorce (14) años, eximiéndose Animalia por cualquier acceso y utilización del Sitio Web no autorizada.</p>
        <h2>13. Publicidad</h2>
        <p>El Sitio Web puede albergar contenidos publicitarios o estar patrocinado. Los anunciantes y patrocinadores son los únicos responsables de asegurarse que el material remitido para su inclusión en el Sitio Web cumple con las leyes que en cada caso puedan ser de aplicación. Animalia no será responsable de cualquier error, inexactitud o irregularidad que puedan contener los contenidos publicitarios o de los patrocinadores.</p>
        <h2>14. Protección de datos</h2>
        <p>Animalia tratará los datos personales recogidos a través de su Sitio Web de conformidad con la Política de Privacidad.</p>
        <h2>15. Derechos de propiedad intelectual e industrial</h2>
        <p>15.1 El Sitio Web está protegido por derechos de propiedad intelectual e industrial. Con carácter enunciativo, que no limitativo, los Contenidos, diseño gráfico, código fuente, logos, textos, gráficos, ilustraciones, fotografías y demás elementos que aparecen en el Sitio Web. Por ello, el usuario reconoce que la reproducción, distribución, comercialización, transformación, y en general, cualquier otra forma de explotación, por cualquier procedimiento, de todo o parte del Sitio Web constituye una infracción de derechos de propiedad intelectual e industrial de Animalia o del titular de los mismos, salvo que el usuario hubiera obtenido la previa autorización expresa.</p>
        <p>15.2 Animalia es el legítimo titular de los derechos de explotación sobre los Contenidos publicados en el Sitio Web, en todo el mundo, por un plazo perpetuo, de manera absoluta y sin límites de ninguna naturaleza. En particular y a modo enunciativo pero no limitativo, Animalia podrá reproducir total o parcialmente, comercializar, difundir, traducir, publicar, imprimir, alterar, transformar, realizar adaptaciones y actualizaciones de los Contenidos y celebrar contratos con terceros para ceder su uso, acordar su distribución e incluso ceder los derechos de explotación.</p>
        <p>15.3 Los logos, marcas, nombres comerciales y otros signos distintivos de cualquier clase contenidos en el Sitio Web están asimismo protegidos por la ley.</p>
        <p>15.4 El usuario no podrá modificar o utilizar dicha propiedad intelectual e industrial de forma que su divulgación suponga un perjuicio para Animalia. Animalia reclamará por los daños y perjuicios derivados del uso indebido por parte de terceros de su propiedad intelectual e industrial.</p>
        <p>15.5 Animalia no concede ninguna licencia o autorización de uso de ninguna clase sobre sus derechos de propiedad intelectual e industrial o sobre cualquier otra derecho o propiedad relacionado en el Sitio Web, los servicios o los Contenidos.</p>
        <h2>16. Notificación de infracciones</h2>
        <p>16.1 En caso de que el usuario infrinja derechos de propiedad intelectual y/o industrial o cualquier otro derecho de terceros, será apercibido por Animalia en el momento en que ésta tenga conocimiento de tales infracciones para que cese en la publicación de los Contenidos infractores. En tal caso, el usuario responderá por tales infracciones y Animalia cancelará el acceso del mismo al Sitio Web.</p>
        <p>16.2 Si cualquier persona o entidad considera que los Contenidos publicados en el Sitio Web infringen sus derechos de propiedad intelectual y/o industrial, sus derechos al honor, a la intimidad, a la imagen o cualquier otro derecho podrá comunicarlo a Animalia por cualquiera de las vías de contacto que figuran en el Sitio Web con el asunto “Vulneración de derechos”, solicitar su retirada y aportar la siguiente información:</p>
        <ol style="list-style-type: lower-alpha;">
        <li>identificación de los derechos protegidos por la legislación vigente que se consideran violados,</li>
        <li>identificación de los Contenidos que presuntamente violan los derechos en cuestión con información razonablemente suficiente para permitir a Animalia ubicar dicho material en el Sitio Web,</li>
        <li>información de los datos de contacto (dirección física o electrónica y número de teléfono) para que Animalia pueda comunicarse con dicha persona o entidad,</li>
        <li>una declaración en la que dicha persona o entidad afirme que la información incluida en la notificación es veraz y exacta y que es el titular de los derechos presuntamente vulnerados o que está autorizado a actuar en nombre de éste, y</li>
        <li>copia del D.N.I, pasaporte u otro documento oficial que acredite su identidad.</li>
        </ol>
        <p>Animalia atenderá dicha petición y si considera que dicha persona o entidad tiene motivos o causas justificadas para solicitar la retirada de tales Contenidos, procederá a su eliminación inmediata del Sitio Web de forma que no sean accesibles por los usuarios ni siquiera desde la memoria caché.</p>
        <h2>17. Legislación y jurisdicción aplicable</h2>
        <p>Los presentes Términos y Condiciones se regirán e interpretarán de conformidad con la legislación española vigente.</p>
        <p>Cualquier controversia, reclamación o disputa en cuanto a la interpretación, ejecución y/o resolución de los presentes Términos y Condiciones se somete a los Juzgados y Tribunales de la ciudad de Barcelona.</p>
        </body>
        </html>